version: '3.1'
services:
  php-fpm:
    build: .docker/php-fpm
    container_name: books-site-php
    working_dir: /app
    volumes:
      - '.:/app'
      - './.docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'

  database:
    image: 'mysql:8.0'
    container_name: books-site-mysql
    working_dir: /app
    volumes:
      - '.:/app'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
      - '3306:3306'

  webserver:
    image: 'nginx:alpine'
    container_name: books-site-nginx
    working_dir: /app
    volumes:
      - '.:/app'
      - './.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8081:80'
